name: Trigger Other Repo Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch in another repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/kewal-d/Source/dispatches \
            -d '{"event_type": "access-file"}'
